/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 aiEyes.gltf
Author: stevencmutter (https://sketchfab.com/stevencmutter)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/dawn-of-creation-point-cloud-a9989c936e764e9d9bf0866571fdd026
Title: Dawn of Creation Point Cloud
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AIEyes(props) {
  const { nodes, materials } = useGLTF('/aiEyes.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.36}>
        <points geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_9.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_11.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_12.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_13.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_14.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_15.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_17.geometry} material={materials['Scene_-_Root']} />
        <points geometry={nodes.Object_18.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/aiEyes.gltf')
